stages:
  winsorize_and_hu:
    cmd: python3 1_winsorize_and_hu.py data/raw data/processed/hounsfield
    deps:
      - 1_winsorize_and_hu.py
      - data/raw/
    outs:
      - data/processed/hounsfield
  windowing:
    cmd: python3 2_windowing.py data/processed/hounsfield data/processed/windowed 40 80
    deps:
      - 2_windowing.py
      - data/processed/hounsfield
    outs:
      - data/processed/windowed
  brain_extraction:
    cmd: python3 3_brain_extraction.py data/processed/windowed data/processed/brain_extracted
    deps:
      - 3_brain_extraction.py
      - data/processed/windowed
    outs:
      - data/processed/brain_extracted
  sort_brain_extracted:
    cmd: python3 5_sort_images.py data/processed/brain_extracted data/processed/sorted_imgs
    deps:
      - 5_sort_images.py
      - data/processed/brain_extracted
    outs:
      - data/processed/sorted_imgs
  sort_no_brain_extraction:
    cmd: python3 6_sort_images_no_extraction.py data/processed/windowed data/processed/sorted_imgs_no_brain_extraction
    deps:
      - 6_sort_images_no_extraction.py
      - data/processed/windowed
    outs:
      - data/processed/sorted_imgs_no_brain_extraction
  process_and_sort_masks:
    cmd: python3 7_process_and_sort_masks.py
    deps:
      - 7_process_and_sort_masks.py
      - GM/ 
    outs:
      - data/processed/sorted_masks/  
