name: CML Workflow for UNet Training on AWS with GPU
on: [push]

jobs:
  deploy-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Deploy runner on AWS
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner launch \
            --cloud aws \
            --cloud-region ap-southeast-1 \
            --cloud-type p2.xlarge \
            --cloud-hdd-size 100 \
            --labels cml-runner

  train-model:
    needs: deploy-and-train
    runs-on: [self-hosted, cml-runner]
    container: 
      image: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.8
          python3.8 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Verify Installed Packages and GPU Availability
        run: |
          pip list
          nvidia-smi
          python -c "import torch; print(torch.cuda.is_available())"
          
      - name: Configure AWS Credentials
        run: |
          dvc remote modify s3-remote access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --local
          dvc remote modify s3-remote secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --local

      - name: Adjust permissions
        run: |
          sudo chmod 777 -R /tmp && sudo chmod o+t -R /tmp

      - name: DVC Pull Data
        run: |
          dvc pull
          dvc repro

      - name: Train the Model
        run: |
          cd unet
          python train.py --epochs 1 --batch-size 4 --learning-rate 0.0001 --gpu 1

      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd unet
          echo "## Training Summary" >> report.md
          cat summary.txt >> report.md
          cml publish training_logs.txt --md >> report.md
          cml send-comment report.md
