name: CML Workflow for UNet Training on AWS with GPU
on: [push]

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up CML
        uses: iterative/setup-cml@v1

      - name: Deploy runner on AWS
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner launch \
            --cloud aws \
            --cloud-region ap-southeast-1 \
            --cloud-type p2.xlarge \
            --cloud-hdd-size 200 \
            --labels cml-runner

  detect-drift-and-train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: 
      image: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.8
          python3.8 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Verify Installed Packages and GPU Availability
        run: |
          pip list
          nvidia-smi
          python -c "import torch; print(torch.cuda.is_available())"
          
      - name: Configure AWS Credentials
        run: |
          dvc remote modify s3-remote access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --local
          dvc remote modify s3-remote secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --local

      - name: Adjust permissions
        run: |
          sudo chmod 777 -R /tmp && sudo chmod o+t -R /tmp
      
      - name: Pull new and current data with DVC and Process data
        run: |
          dvc pull 
          dvc repro

      - name: Run data drift detection
        run: |
          python detect_drift.py --old data/processed/sorted_imgs/train --new data/oasis/ct_norm_resized
        id: detect_drift
      
      - name: Fine-tune model if drift detected
        if: steps.detect_drift.outputs.drift-detected == 'true'
        run: |
          cd unet
          python fine_tuning.py --epochs 20 --batch-size 5 --learning-rate 0.0001 --gpu 0 --dir-img '../data/processed/sorted_imgs/train' --dir-mask '../my_dvc_project/data/processed/sorted_masks/train' --dir-img-val '../data/processed/sorted_imgs/val' --dir-mask-val '../data/processed/sorted_masks/val' --load 'checkpoints_bet_alt/early_stopping_model.pth' --wandb

          dvc push
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Model fine-tuned due to data drift"
          git push


      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "## Training Summary" >> report.md
          cat summary.txt >> report.md
          cml publish training_logs.txt --md >> report.md
          cml comment create report.md
